version: '3'

services:
  client:
    build:
      context: frontend
      dockerfile: Dockerfile
    image: nodejs
    container_name: client
    restart: unless-stopped
    env_file: frontend/.env
    environment:
      - MONGO_USERNAME=$MONGO_USERNAME
      - MONGO_PASSWORD=$MONGO_PASSWORD
      - MONGO_HOSTNAME=db
      - MONGO_PORT=$MONGO_PORT
      - MONGO_DB=$MONGO_DB 
    ports:
      - "80:8080"
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    networks:
      - app-network
    command: yarn dev
    # command: ./wait-for.sh db:27017 -- /home/node/app/node_modules/.bin/nodemon app.js

  server:
    build:
      context: server
      dockerfile: Dockerfile
    image: nodejs
    container_name: nodejs
    restart: unless-stopped
    env_file: server/.env
    environment:
      - MONGO_USERNAME=$MONGO_USERNAME
      - MONGO_PASSWORD=$MONGO_PASSWORD
      - MONGO_HOSTNAME=db
      - MONGO_PORT=$MONGO_PORT
      - MONGO_DB=$MONGO_DB 
    ports:
      - "80:8080"
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    networks:
      - app-network
    command: yarn dev
    # command: ./wait-for.sh db:27017 -- /home/node/app/node_modules/.bin/nodemon app.js

volumes:
  node_modules:

networks:
  app-network:
