version: "3"
services:
  # manage the docker instances remotely
  portainer:
    image: portainer/portainer
    ports:
      - "9000:9000"
      - "8000:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

  # data storage
  mongodb:
    image: mongo:latest
    container_name: "db"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    ports:
        - 27017:27017

  # cluster of nats servers
  nats:
    image: nats
    ports:
      - "8222:8222"
  nats-1:
    image: nats
    command: "--cluster nats://0.0.0.0:6222 --routes=nats://ruser:T0pS3cr3t@nats:6222"
  nats-2:
    image: nats
    command: "--cluster nats://0.0.0.0:6222 --routes=nats://ruser:T0pS3cr3t@nats:6222"


volumes:
  portainer_data:

networks:
  overlay:


# should be able to zip data and send it to google drive or s3